"""test data

Revision ID: 7a364a5273cc
Revises: 736c7d11d105
Create Date: 2024-07-23 20:21:04.956843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a364a5273cc'
down_revision: Union[str, None] = '736c7d11d105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    connection = op.get_bind()
    op.execute("""INSERT INTO "user" (name, second_name, avatar)
    VALUES
    ('John', 'Doe', 'avatar1'),
    ('Jane', 'Doe', 'avatar2'),
    ('Bob', 'Smith', 'avatar3'),
    ('Alice', 'Johnson', 'avatar4'),
    ('Charlie', 'Brown', 'avatar5');
    """)

    connection.commit()

    op.execute("""INSERT INTO genre (name)
    VALUES ('Romance'),
    ('Fantasy'), 
    ('Science Fiction'), 
    ('Mystery'), 
    ('Horror');
    """)

    connection.commit()


    op.execute("""INSERT INTO book (name, page_count, price, author_id)
        VALUES
    ('Name1', '100', '1000', 0),
    ('Name2', '200', '2000', 1),
    ('Name3', '300', '3000', 2),
    ('Name4', '400', '4000', 3),
    ('Name5', '500', '5000', 4);
    """)

    connection.commit()

    op.execute("""INSERT INTO book_genre (book_id, id)
        VALUES
    (0, 0),
    (1, 0),
    (1, 1),
    (2, 0),
    (2, 1),
    (2, 2),
    (3, 0),
    (3, 3),
    (4, 4),
    """)

    connection.commit()
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

def downgrade() -> None:
    pass
